NBISweden/urdr

Dockerfile
README.md
docker-compose.yml

First draft for the project setup. I thought Redmine should always be an external project that we download
then when starting our containers we would  start redmine as well.

first draft for the setup

---

backend/api/api.go
backend/internal/redmine/api.go
frontend/src/login.tsx

- Sessions work with a cookie called urdr_session
- The server stores whether the user is logged in or not in that session
- This implies the browser won't be able to interact with the api endpoints unless logged in
Fixes #41

Set up server-side session handling for login

---

.github/dependabot.yml

Dep updates for:
- Golang modules
- npm packages
- Dockerfile

Add explicit config for dependency updates

---

frontend/src/App.tsx

without this, the `reporter.tsx` file isn't loaded

fix capital letter in import

---

.gitignore
backend/api/api.go
backend/internal/redmine/api.go

This PR stores the user info in the session.

Set user struct in session

---

.gitignore
README.md
backend/internal/redmine/api_test.go

- Update gitignore
- Add tests for redmine api calls
- Add env file for tests

Add minimal tests in redmine package

---

backend/api/handlers.go

Return 500 if we cannot create an entry

---

frontend/public/index.html
frontend/src/components/HeaderRow.tsx
frontend/src/components/Row.tsx
frontend/src/index.css
frontend/src/pages/Report.tsx

This PR provides basic styling for the section with recent issues and the save button.
More details will be added when more content is there. 
The button might become a reusable Button component in the future. 
The google font Lato (SciLifeLab recommendation) is used. 
Colors and sizes follow the design rules. 
This fixes #95

basic styling recent-section

---

backend/api/api.go
backend/api/handlers.go
backend/docs/docs.go
backend/docs/swagger.json
backend/docs/swagger.yaml
backend/internal/redmine/api.go
backend/internal/redmine/api_test.go

- Add route for spent time withing time range
- Add func for fetching time spent from redmine
- Add test for new function
- Add function for mapping issues and activities
- Add spentTimeWithinDateRangeHandler func
- Add missing status code in docs
- Update docs with new endpoint

Add endpoint for fetching spent time entries within a time range

---

node/Dockerfile

found a bug in the copy statement

Fix permission of copy

---

.github/workflows/codeql-analysis.yml
.github/workflows/golangci-lint.yml
.github/workflows/linter.yml
.github/workflows/super-linter.yml

* Cleanup
* Only run on pull requests
* Ignore auto-generated documentation/code
Closes #142

Linter updates

---

docker-compose.yml
frontend/package.json
frontend/src/pages/Login.tsx
frontend/src/pages/Report.tsx
urdr.env.default

This PR replaces the hardcoded api url by the env variable provided.

Using env variable to set the api endpoint

---

README.md

Updating the readme to make it fit our setup after changing the Dockerfile.
fixes #119

update frontend section in Readme

---

backend/api/handlers.go
backend/docs/docs.go
backend/docs/swagger.json
backend/docs/swagger.yaml
frontend/src/components/Cell.tsx
frontend/src/components/Row.tsx
frontend/src/pages/Login.tsx
frontend/src/pages/Report.tsx

- The backend still stores the user ID, but does not pass it on to the frontend.

Remove the user ID from the frontend and backend

---

backend/api/api.go
backend/api/handlers.go

added activity endpoint

---

.github/workflows/test.yml

This is a starting point for having the go unit tests run after every push.

Add action for running unit tests

---

.gitignore
backend/api/handlers.go
backend/api/handlers_test.go
backend/internal/database/database_test.go
backend/internal/redmine/models.go

- Add redmine data models
- Add tests for api handlers

Add unit tests for endpoint handlers

---

.github/workflows/apidocs.yml
backend/api/handlers.go
backend/docs/docs.go
backend/docs/swagger.json
backend/docs/swagger.yaml

- Add action for making sure docs can be created
- Update comments for api docs
- Update docs

Updates on Swagger docs

---

frontend/src/components/QuickAdd.tsx
frontend/src/components/Row.tsx
frontend/src/pages/Report.tsx

Quick and dirty way to redirect to Login page ("/") when we get 401 back.
Closes #212

Redirect to Login page when session expires

---

frontend/src/components/HeaderUser.tsx
frontend/src/index.css
frontend/src/pages/Report.tsx

- Add styling for new header
- Add HeaderUser to Report page
- Add HeaderUser component with logout option
Closes #198
Closes #199

Show username and add logout button

---

backend/api/handlers.go
frontend/package-lock.json
frontend/package.json
frontend/src/components/Row.tsx
frontend/src/components/TimeTravel.tsx
frontend/src/index.css
frontend/src/pages/Report.tsx
frontend/src/utils.tsx

- Add weeknumber package
- Add styling for new elements
- Move getFullWeek to utils
- Allow passing query string in recent issues
- Add TimeTravel component
- Implement week travelling in the Report page
- Make rows update on week change

Add basic time travelling functionality

---

frontend/package-lock.json
frontend/package.json
frontend/src/components/Cell.tsx
frontend/src/components/Row.tsx
frontend/src/icons/grip-vertical.svg
frontend/src/index.css
frontend/src/pages/Report.tsx

- you should be able to drag and drop favorites to change their order
- unsaved changes in the spreadsheet should not disappear
- react-beautiful-dnd is added as dependency
- snowpack is downgraded to version 3.8.6
This is rebased on develop including week traveling feature (#238 ). It does not include the finished QuickAdd feature yet. (#240).
It fixes #216

Drag and drop for favorites

---

frontend/package-lock.json
frontend/package.json
frontend/src/components/TimeTravel.tsx
frontend/src/index.css
frontend/src/pages/Report.tsx

- Add react datepicker package
- Add styling of date travelling
- Add basic data picker for travelling
- Add with portal
- Add year dropdown and show two months

Add basic date picker for time trevalling

---

frontend/src/components/TimeTravel.tsx

We only want to display the current month for now.
Closes #270

Remove two months display

---

frontend/src/components/Cell.tsx
frontend/src/components/Row.tsx
frontend/src/pages/Report.tsx

Now the right time entries should be fetched and displayed in the right columns.

replace toISOString with date-fns function

---

frontend/src/components/Cell.tsx
frontend/src/components/Row.tsx
frontend/src/pages/Report.tsx
production/http-staging.conf

This includes the date related fixes we made to fetch the right time entries.

1.0.1-beta release

---

production/Dockerfile
production/README.md
production/docker-compose.yml

In order to achieve this, a user has been created within the urdr image and the production compose file refers to this user.

Set urdr as service user

---

frontend/src/components/TimeTravel.tsx

Remove portal from date picker

---

backend/api/getActivitiesHandler.go

This PR ensures that the activities returned from the `/api/activities` GET endpoint are ordered by name.
The changes include intercepting the response of the proxied request to Redmine, unmarshalling the data, sorting it, and re-marshalling it before sending it back to the frontend.
Closes #337

Order activities by name

---

frontend/src/components/AuthProvider.tsx

removing the user from the local storage after logout

---

frontend/src/pages/Report.tsx

Possibly solves #349 . Could not reproduce that case. But helps to avoid unnecessary rendering anyways, while the page is redirected.

added validation to avoid render if user is set to null

---

frontend/src/pages/Report.tsx

This should be able to handle the cases of quiting or reloading the page.
Closes #369

Add hook for handling unsaved data on reload/quit

---

frontend/src/components/Cell.tsx
frontend/src/pages/Report.tsx

A new version of the bugfix for #299 .
No major refactoring, but hopefully much simpler.

Fixing removed unsaved entries - new version

---

frontend/src/pages/Report.tsx

using previous function to do the row sum

---

frontend/src/components/Row.tsx
frontend/src/pages/Report.tsx

fixing accessibility inputs

---

frontend/src/pages/Report.tsx
frontend/src/utils.tsx

This PR is just to make a small refactoring moving a function from the utils to the Report, where it belongs. I have already talked about it with Henrike.

Moved function to the report

---

frontend/src/components/Cell.tsx
frontend/src/index.css

This PR  relates to #424 .
It removes some settings and updates others to improve the comment. To close the issue the events to close the text area should be treated
- [ x] Bug fix (non-breaking change which fixes an issue)
[](url)
Add or edit a comment

Removed and updated some props to fix comment size

---

frontend/package-lock.json
frontend/package.json
frontend/src/index.css
frontend/src/pages/Report.tsx

This PR closes #401.
- Visualise a loading overlay with a spinner when saving changes
- Added two new packages to achieve this
- A rebuild is needed due to new dependencies
- Check out and test normally. The new functionality will be shown after clicking on saving changes

Show loading overlay when saving changes

---

frontend/src/index.css

Changed positioning to be absolute instead of fixed.
Fixes #425

Fix swimming box on scroll

---

frontend/src/components/Row.tsx
frontend/src/pages/Report.tsx

Sum column/row should use aria-label instead of aria-labelledby to work properly.

Fix accessibility issues.

---

frontend/src/components/QuickAdd.tsx

Bug in the css of footer because of a space

Bug of validationn box moving the iput because of missing space

---

frontend/src/components/Row.tsx

The favorite buttons used to have a title on the image rather than the button.

Move title attr to button from image

---

.github/workflows/create_packages.yml
production/docker-compose.yml

Correct usage of latest tags

---

frontend/src/template.hbs
frontend/webpack.config.js
frontend/webpack.config.prod.js

The hbs template does not get the title value replaced. This shopuld work for now.

Hardcode page title

---

.github/dependabot.yml

So far only the dev environment was getting updates.

Search for Docker related dep updates in prod

---

.github/dependabot.yml

Trigger for dependabot updates.

Get updates of dev node server

---

frontend/src/components/QuickAdd.tsx

If a user fills in a valid issue id, this should be automatically selected.
Kudos to @konere10 who thought of this!

Autoselect valid issue ids

---

frontend/src/components/QuickAdd.tsx

This PR closes #544 
- After selecting an issue, if an activity was previously selected, we keep that activity

Fix wrong activity selection bug

---

frontend/src/pages/Report.tsx

This PR #545 
- New toast was added

Add time entries up-to-date toast

---

frontend/src/components/QuickAdd.tsx

This PR closes #538 
- Prevent default scrolling with up n down arrows

Fix suggestions kbd nav

---

frontend/src/components/Cell.tsx

- Make sure that we unhighlight when tabbing from the comment triangle to the next node

Fix row highlighting bug

---

.github/workflows/create-test-package.yml

- New actions workflow to work with urdr-web test images

Add action for urdr-web test image

---

.github/workflows/create-test-package.yml

Test server images are not built at the moment.

Fix build command

---

.gitignore

Updating gitignore for Intelijj Idea.

Updated gitignore for idea

---

README_testinstall.md

... with pre-built images on SNIC SSC.
New file with instructions.

Instructions on what is needed to setup a test site

---

frontend/src/pages/SpentTime.tsx
frontend/src/utils.tsx

There was a bug that made it so that only the first batch could be retrieved.

Rework unlimited time entries fetching

---

frontend/src/index.css
frontend/src/pages/VacationPlanner.tsx

- Visualise weekly amount of reported vacation in the last year

Visualise reported weekly vacation in planner

---

frontend/package-lock.json
frontend/package.json
frontend/src/pages/SpentTime.tsx

This PR relates to issue #576 to try out the react minimal pie chart.
This issue adds a pie chart with react-minimal-pie-chart library and uses the data from Redmine to visualize with random colors at the moment. It's a POC and can only be seen when navigating to /spent_time through the url.
Added a dependency to react-minimal-pie-chart according to the projects read me file.
- A rebuild is needed due to new dependencies:
1. docker-compose down node-urdr --volumes
2. docker-compose build node-urdr
3. docker-compose up node-urdr

From issue #576 try out visualization with React Minimal Pie Chart

---

frontend/src/pages/VacationPlanner.tsx

This PR closes #597
- Make sure that someone is not allowed to report vacation if entries have already been reported.

Stop vacation report if entries exist

---

frontend/package-lock.json
frontend/package.json
frontend/src/index.css
frontend/src/model.tsx
frontend/src/pages/VacationPlanner.tsx

- Added dropdown to switch between groups
- Better feedback for invalid vacation periods
- Real data on timeline plot
- Realised PO wants to mark weekends in some way. This is not straightforward with this library...

Display real entries in timeline

---

frontend/src/pages/VacationPlanner.tsx

This PR closes #621 
- Added custom comment for absence reports

Use custom comment in absence planner

---

frontend/src/components/EditPeriodDialogProvider.tsx
frontend/src/pages/AbsencePlanner.tsx

- Fixes so that we can correctly update our absence periods.

Fix edit period date picking conflict

---

production/docker-compose.yml

This PR closes #685
Added `restart: always` to `nginx` section of production `docker-compose.yml` file.

Ensure that the Urdr web service restarts

---

.github/dependabot.yml

This PR relates to #692 
Enable Dependabot for the `frontend` directory.

Enable Dependabot for the `frontend` directory too

---

backend/Dockerfile

Running the project was not working due to miss match between versions 
Specified alpine version in Dockerfile

fix: docker file updating version

---

frontend/src/components/LoginHeader.tsx
frontend/src/index.css

This PR closes https://github.com/NBISweden/urdr/issues/949
- Added image to login-page. 
Check out this branch and have a look at the image.

Style: add urdr-image to login-page

---

backend/api/getPriorityEntriesHandler.go

Use `&` for parameter delimiter.

fix: Fix boo boo

---

node/Dockerfile
production/Dockerfile.nginx

This PR closes #1046
- make git requirements in `node/Dockerfile` and `production/Dockerfile.nginx` less strict.
- checkout this branch
- run `docker compose build`
- see a successful build process

make git requirements in Dockerfiles less strict

---

frontend/webpack.config.prod.js

This PR closes [issue number] and relates to [issue or PR number].
- A certain branch in other repos is needed
- A rebuild is needed due to new dependencies
- Requires new configuration settings
- Instructions on how to test

Hotfix Release/20250319

---

production/Dockerfile.nginx

Second hotfix:  The variables set in the Dockerfile need to be in the correct `FROM` section to have any effect.

fix: Move the setting of the variables in the Dockerfile

---

frontend/package-lock.json
frontend/package.json
frontend/src/components/Cell.tsx
frontend/src/components/CustomMouseSensor.tsx
frontend/src/components/Draggable.tsx
frontend/src/components/Row.tsx
frontend/src/pages/Report.tsx

This PR closes #1081
- removed deprecated dependency `react-beautiful-dnd`
- added new dependency for drag and drop `dnd-kit`
- updated frontend dependencies (following this repository's readme)
- look at `/report`
- if you don't have any favorite issues, mark some issues as favorites
- try to change their order using drag and drop
- make sure the order remains when reloading a page
- make sure all interactive elements inside a favorite row work as expected: 
- the star button
- the link to redmine
- the input field to change the favorite's title
- the cells for entering hours
- the comment functionality for time entries
Basically, everything should work the same way as it does currently on `develop`.
To add the new dependency, I followed the description in this repository's readme. The …

Replace dependency react-beautiful-dnd

---

frontend/package-lock.json
frontend/package.json

This is a trivial addition to Henrike's PR:
Forgot to remove dependencies on the old dnd library.

fix: Remove dependency on old dnd library

---

frontend/Dockerfile.update-package-lock
node/Dockerfile
production/Dockerfile.nginx

This PR closes #1082  and relates to #999 #1015 #1021 #1038 #1040 #1065
Node versions were updated to 20.19.0 in the following files:
* `node/Dockerfile`
* `frontend/Dockerfile.update-package-lock`
* Twice in `production/Dockerfile.nginx`
- A certain branch in other repos is needed
- A rebuild is needed due to new dependencies
- Requires new configuration settings
- Instructions on how to test

fix: Update to Node 20.19.0

---

frontend/package-lock.json
frontend/package.json
frontend/src/components/LoadingOverlay.tsx
frontend/src/index.css
frontend/src/pages/AbsencePlanner.tsx
frontend/src/pages/Login.tsx
frontend/src/pages/Report.tsx

This PR closes https://github.com/NBISweden/urdr/issues/1089
- Removed the library `react-loading-overlay-ts`.
- Added a new component called `LoadingOverlay.tsx`.
- Reused the css-class loading-overlay but updated it a little. 
1. Check out this branch and make sure it works. A tip is to mess around with the network settings in your browser so the loading takes longer.

Refactor: replace overlay library with a new component

---

frontend/package-lock.json
frontend/package.json
frontend/src/pages/SpentTime.tsx
node/Dockerfile

This PR closes #342
All changes:
* Add missing dependency on `@dnd-kit/utilities`.
* Replace dependency on `react-google-charts` with dependency on `react-minimal-pie-chart`.
* Replace dependency on `styles-loader` with dependency on `style-loader`.
* Regenerate `package-lock.json`.
* Import `./model` instead of `model` in `pages/SpentTime.tsx`.
* Move installation of `git` package into the `RUN` block where it's used, in the Dockerfile.
With this PR, a build of the code should generate no `npm warn` messages about deprecations etc.

Minimize npm dependencies

---

.github/workflows/super-linter.yml
.super-linter.yml
frontend/.eslintrc.json
frontend/src/components/VacationOverview/GroupSelect.tsx
frontend/src/components/VacationOverview/VacationOverview.tsx
frontend/src/components/VacationOverview/VacationTable.tsx
frontend/src/components/VacationOverview/types.ts
frontend/src/components/VacationOverview/utils.ts
frontend/src/index.css
frontend/src/pages/AbsencePlanner.tsx

This PR closes #1094.
Adding a vacation table according to a simple design sketch showing the vacations of colleagues.
Added a  new component called VacationOverview. A dropdown where the user can choose a group.The table showing three months from now with months, weeks and date ranges. The vacation will be marked as a grey cell in the table.
In order to test you need to have the group information available in the local database. In the read me file there is a section called "Urdr set up" and there is mentioned that the groups and users needs to be updated. In development this can be done by:
`./backend/sql/update-users-groups.sh  "$REDMINE_REPO"/docker-compose.yml backend/database.db`
where `"$REDMINE_REPO"` is some path to the cloned `ops-redmine` repository. Please look into the read …

feat: simple table with dropdown and groups- #1094

---

.github/dependabot.yml

chore(deps): Docker dependencies can't be grouped

---

frontend/src/components/VacationOverview/VacationTable.tsx
frontend/src/components/VacationOverview/types.ts
frontend/src/components/VacationOverview/utils.ts
frontend/src/index.css
frontend/src/pages/VacationOverview.tsx

This PR closes issue number #1097
- add arrow buttons to the vacation overview to move weeks back and forward
- to prepare, add at least one planned absence period for at least one of the staff members in your team (e.g. for yourself)
- go to the vacation overview
- try out the arrow buttons 
- the weeks displayed in the table header should move backwards / forwards
- the planned absence period should be displayed correctly
- The issue #1097 contained two parts: the arrow buttons and a dropdown for choosing a month manually. I think that these could be split in two; this PR only covers the arrow buttons. I created a follow-up issue #1166 .
- In the [design sketch](https://github.com/NBISweden/urdr/issues/1066), the arrow buttons were placed below the table. As the table can become quite …

Add arrow buttons to vacation overview
