NBISweden/urdr

.github/workflows/linter.yml

Fix linter by switching from the "slim" to the full linter.
See https://github.com/github/super-linter/issues/2153#issuecomment-983616741

Switch to non-slim linter to fix `cgo` issues

---

README.md
backend/.env.default
backend/api/api.go
backend/internal/config/config.go
backend/internal/redmine/api.go
frontend/package.json
frontend/src/pages/Reporter.tsx
node/Dockerfile

- Remove redmine admin token var
- Remove description about admin tokens
- Use session api tokens
- Rework Login to use redmine account endpoint
- Use user api token for issues and time entries
- Do not impersonate user

Utilise user tokens for consuming the redmine api

---

backend/api/api.go
backend/internal/redmine/api.go

This solution serves both issues and spent time from a single endpoint called `spent_time`.
This might be tested after logging in by browsing to:
localhost:8080/api/spent_time?start=2022-01-01&end=2022-03-01

Alternative solution for spent time retrieval

---

frontend/package-lock.json
frontend/package.json
frontend/src/pages/Login.tsx

Node.js recommends to use the `Buffer` module instead of `btoa` for base64 encoding. 
It's a standard module of Node.js and should be included in the installation, however, Snowpack had problems finding it. 
Others have faced this issue before and [here](https://github.com/withastro/snowpack/discussions/1132) the maintainer of Snowpack suggest using the npm package "buffer" instead, so that's what I did. 
To test this, you will have to build the `node-urdr` container to include the new package.
This fixes #108

Fix base64 encoding in frontend

---

frontend/src/components/Cell.tsx
frontend/src/components/HeaderRow.tsx
frontend/src/components/Row.tsx
frontend/src/index.css
frontend/src/pages/Report.tsx

The interface now shows input cells for the whole week instead of one day. 
It will always show Monday to Friday of the current week, starting with Monday.
It's possible to add time entries in several input cells and save them with one click on the "Save changes"-button.
Limitations:
- there is still no proper error handling / input validation yet
- no existing time entries are fetched from the backend. Thus it's only possible to add new entries (not editing or deleting existing ones).
This fixes #145 .

Enabling timelogging for whole week

---

frontend/update-package-lock
frontend/update-package-lock.docker

Do like this 
update the dependencies or add dependency in package.json
run ./update-package-lock
git add package.lock and the newly created package-lock.json 
and push both changes to git.
@kusalananda The bash script might need to do some more clever stuff please have a look at it. 
@HenrikeW this will update the lock file to the latest packages according to the update rules in package.json 
it might not be what we want but if the rules are set ok it wont brake so it can be a good idea to get the latest changes?

A way of update the package-lock.json in the container

---

backend/api/handlers.go
frontend/src/components/Cell.tsx
frontend/src/components/Row.tsx
frontend/src/pages/Report.tsx

OBS: This PR is based on the branch @kusalananda is working on. It adds the frontend part for handling existing time entries. 
The UI now shows all time entries for the user's recent issues in the corresponding cells. 
On save, all changes are saved. This can now be modified entries, deleted entries (sent as TimeEntry objects with 0 hours) or entirely new entries.
In case you wonder about the `setTimeout` in the Row component, line 56: without this, when saving, changed values would jump back to the old value for a short moment because of asynchronous fetching. This workaround removes the effect. 
If you have any better idea of solving the problem, please let me know!

UI support for existing entries

---

frontend/src/pages/Report.tsx

A new state variable `filteredRecents` is added to keep a filtered list of recent issues. This one keeps all recent issues minus those that already appear in the list of favorites. 
This way, `recentIssues` keeps an unmodified list of recent issues fetched from the backend on first page render. 
This one can be reused when favorites are modified and no additional call to `/recent_issues` is necessary. 
Also some minor refactoring with using the spread operator instead of `map` to create shallow copies of arrays.
Fixes #217

Reduce api calls for favorites

---

backend/api/getPriorityEntriesHandler.go

This PR is a very minor modification to a single file that moves a test of a returned value semantically closer to the function call that produced it.
This is the only code change that I found that was relevant in relation to issue #247 
In my opinion, this closes #247

Check returned values closer to function call

---

frontend/src/components/LoginHeader.tsx
frontend/src/pages/Login.tsx

The `<Header />` component was created when we made the login page, under the assumption that it would be reused on the report page. This turned out not to be the case and now there are several components containing the word "Header". 
I figured it would be better to be more precise here to avoid confusion.

rename Header to LoginHeader

---

frontend/src/components/QuickAdd.tsx
frontend/src/icons/plus.svg
frontend/src/index.css
frontend/src/pages/Report.tsx

This PR is about the "Save changes" and the "add" button. The logout button also looks different, **but you can ignore that**. It will be changed in a later PR. 
Some comments:
- it was pointed out that the enabled and disabled buttons were hard to tell apart. I read up on accessibility for disabled buttons and learned that it's best to avoid them entirely and instead have meaningful error messages, so that's what I did. 
(In case you're curious: https://axesslab.com/disabled-buttons-suck/)
- the box-shadows didn't actually show in the layout, I think there was some mistake in how they were written. So I removed them.
Fixes #279 and fixes #241
EDIT: also fixes #285

improve button styling

---

frontend/src/components/HeaderRow.tsx
frontend/src/components/Row.tsx
frontend/src/index.css
frontend/src/pages/Report.tsx
frontend/src/utils.tsx

The dates are now displayed in the format specified in the mockup: "Mon 21/5"
When the window is smaller than the width that would fit this format, the weekday is removed: "21/5"
The `useViewport` hook built for this can potentially be reused in the future to make other parts of the UI more responsive.
This fixes #282 and fixes #286

responsive dates & updated list layout

---

backend/api/api.go
backend/api/handlers_test.go
backend/api/postTimeEntriesHandler.go

This PR addresses the issue of sessions not being extended on the client side.
The current approach is to regenerate a user session upon a successful POST request to the time entries handler.
Closes #317

 Add attempt to extend sessions

---

frontend/src/components/Cell.tsx
frontend/src/model.tsx
frontend/src/pages/Report.tsx

This PR makes sure a user can only input positive numbers up to 999.99999999.... with an unlimited number of decimals behind the delimiter. This is mainly done trough three regex in Cell.tsx. They ensure that 
- only numbers 0-9 and the period . are allowed
- not more than 3 numbers before the period are allowed
- no second period is allowed (which would be something like 22.33.44)
Previously, the user's input would immediately be turned into a number by the + operator in this line
`hours: +event.target.value,`
Using that operator gives errors when a user is in the middle of typing and the cell says e.g. "2."
Therefore, the `hours` are now saved as a string in the `newTimeEntries` array that keeps track of changes, and only converted into a float right before save. 
Fixes #298

limit user input in cells

---

backend/internal/config/config.go
frontend/src/components/Row.tsx
frontend/src/utils.tsx
urdr.env.default

Requires changing variable name in urdr.env so that the Redmine URL can be picked up by Snowpack. Fixes #344

Link issues to Redmine

---

README.md
backend/internal/config/config.go
urdr.env.default

In production, backend and frontend need different URLs to Redmine, so we must use different variables in the env for that.

Must use different URLs to Redmine for frontende and backend

---

frontend/src/index.css

So that it does not look like a button, we had some user feedback about it.

In the quick add, moving the feedback icon to appear inside the input

---

frontend/src/components/Cell.tsx
frontend/src/pages/Report.tsx

This PR closes #432
The onChange listener does not detect ESC and delete key events upon first change. Therefore we use a onKey listener to figure out whether a time entry needs to be deleted.
- Follow the instructions of the bug report written by @HenrikeW

Capture key events for time entry deletion

---

frontend/src/components/QuickAdd.tsx
frontend/src/index.css
frontend/src/pages/Report.tsx

This PR is to fix a bug introduced by the last commit in the previous PR. The change height: 100vh in the loading-overlay class caused the scroll to stop working. Now the class is only set when the spinner is shown, to restore the page scroll
This PR closes #441
Scroll and it works

bug fix introduced by the last commit in the footer

---

.github/workflows/create_packages.yml
production/README.md
production/docker-compose.yml

This PR closes #446 
Added a GitHub actions workflow to build and push images to ghcr
- We'll make a new release and see if it works as expected

Add create packages workflow for releases

---

.github/workflows/create_packages.yml

This PR closes #465 
- The action is now using the head ref of the pr, and is triggered when a pr is closed and merged.
- Making a new release

Fix action for creating release images

---

frontend/src/components/Row.tsx
frontend/src/index.css
frontend/src/pages/Report.tsx

**NOTE: Before this PR is merged, the help page needs to be changed according to the changes in design. 
If you approve, let me know so that I can update the help page before you merge.**
This PR closes #443.
- the eye icon was replaced with an X 
- X and star icon were moved to the left of a row for aesthetic reasons
- the distance between the two icons was increased to improve usability
- the white margin below the header was decreased. In this process, unnecessary `div`s were removed
- the page should work in the same way as before. Test if it does.
- The way GitHub marks changes it looks like a lot has changed in the JSX code in Report.tsx. 
In fact, only two divs were removed, the one starting in line 563 (className="usr-header") and the one starting in line 576 (className="main").
- …

Design tweaks

---

backend/api/recentIssuesHandler.go

This PR closes #290 
We now return a "Vacation row" if there is no time entries logged by the user.
- Delete all time entries from your user
- Log in and force reload

Return vacation if time entries don't exist

---

frontend/src/components/HeaderUser.tsx
frontend/src/index.css

This PR closes #461
- The dropdown was replaced by a navigation bar, which makes the website more accessible when using the keyboard.
- Try keyboard navigation on the report page

Replace dropdown with navigation bar

---

frontend/src/pages/Report.tsx

This PR closes #476 
The case of entering a negative year has now been handled.
- Navigate to a year with a negative number.

Stop users from browsing to nagative years

---

backend/api/loginHandler.go

This makes sure that the basic auth popup is no longer shown by the browser.
This PR closes #475 
- The header that was being used by Chrome to display the auth pop-up has now been dropped from our server's http response.
- Attempt to log in with invalid creds on Chrome

Delete www-authenticate header from login response

---

frontend/src/components/Cell.tsx
frontend/src/components/Row.tsx
frontend/src/index.css

This PR closes #485 
- Added on focus and on blur logic for rows
- Fixed background of star icon
- Play around with selecting the inputs and comments of the rows
- Use keyboard navigation

Highlight rows on focus

---

frontend/src/components/Row.tsx
frontend/src/index.css
frontend/src/pages/Report.tsx

This PR closes #482
- Made all total hours cells non navigatable
- Removed no longer used class from CSS
- Test using keyboard nav

Make total hours cells non-navigatable

---

frontend/src/components/Cell.tsx

This makes sure that you can't highlight multiple rows after selecting the comment area box.

Update onBlur func of text area

---

frontend/src/components/Row.tsx
frontend/src/icons/caret-down-fill.svg
frontend/src/icons/caret-up-fill.svg
frontend/src/icons/chevron-double-up.svg
frontend/src/index.css
frontend/src/pages/Report.tsx

This PR closes #470
- a section was added in which hidden rows are rendered
- a button was added to switch between showing and not showing that section. The default is to not show it.
- a button in each hidden row was added to move the row back to the list of recent rows
- the functionality to toggle favorites was adjusted so that even hidden rows can become favorites in one click
- Go to the report page
- Try to toggle the hidden-section with the new button
- If you don't have hidden rows yet, try to hide some from the recent-section
- try to un-hide a hidden row by clicking on the double-arrow up
- try to make a hidden row a favorite by clicking on the star
- try to reload the page and make sure the right favorites and hidden rows are loaded. (Using the toggle icons for …

Add section for hidden rows

---

frontend/src/pages/Report.tsx

This PR closes #491
- the function `getAllEntries` was changed to accept a single array of IssueActivityPairs (i.e. rows) as an argument
- where it's called, the hidden rows are included in the argument array (previously, the function took two arrays as arguments, which were the recent rows and the favorite rows). The function is called on page load as well as after successful save. 
- go to the report page in a week that has time entries on favorite, recent and hidden rows. You should see all of them.
- make a change in a time entry in a hidden row and save. The sum should be correct both before and after save.
- un-hide the row you've just made a change in. It should move to the recent section together with all its entries.
- to make sure no previous functionality broke, feel free to …

populate hidden rows with time entries

---

frontend/src/index.css

This makes sure that the border is also visible on Safari.
#260 
Updated border style to solid, instead of inset, which makes the button visible on all tested browsers.
- Checkout this branch and test on a safari web browser.

Make sure triangle is visible on Safari

---

frontend/src/components/Cell.tsx
frontend/src/components/Row.tsx

The event handlers now use a arrow fn so that the fns do not fire everytime a component rerenders. Also, now only one row may be selected at a time.
This PR closes #523 
- Event handlers are passed via props using arrow funcs
- We call the correct fn upon ESC when closing the comment area

Rework focus and blur event handlers

---

frontend/src/components/Row.tsx
frontend/src/index.css
frontend/src/pages/Help.tsx
frontend/src/pages/Report.tsx

This PR closes #224
- Updated the issue-activity display in rows with a text area so that custom names can be given to favorite issues
- Original names are displayed on hover using a tooltip

Give custom names to favorite rows

---

backend/api/api.go
backend/api/handlers_test.go
backend/api/issueSearchHandler.go
backend/api/models.go
frontend/src/components/QuickAdd.tsx
frontend/src/index.css
frontend/src/pages/Help.tsx

This PR closes #341 
- Free text issue search is now possible with autocompletion

Advanced search

---

frontend/src/components/Row.tsx
frontend/src/pages/Report.tsx

There was a success toast for saved custom names shown every time any changes were saved.
- introduced state variable that tracks if any custom name has been changed
- when pressing "Save changes", an attempt to save custom names is only made if any custom name has changed
- There is only one Toast message for "All changes saved", no specific one about the names. 
- If anything goes wrong in the save with either time entries or custom names, a generic failure message will be shown.
- Try to make some changes and save

Remove unnecessary success toast

---

frontend/src/components/QuickAdd.tsx
frontend/src/index.css

- Added handleAutocompleteNavigation to handle arrow navigation over suggestions
- Added handleInputToAutocompleteFocus to handle the focus switch from search input to suggestions list

Rework search suggestions navigation

---

frontend/src/components/QuickAdd.tsx
frontend/src/pages/Report.tsx

There were some places left where we used `alert`. All of them are now replaced with our own Toast, type "warning".
- because the list of toasts is handled in Report.tsx, a handler function was created and passed on to the child component that needed it (QuickAdd.tsx)
- alerts in QuickAdd and Report were replaced with toasts.
Just one example.
Most of the cases are error handling for API requests failing etc, so hard to test. 
The one that can be tested is the one on the screenshot above:
Try to add an issue/activity pair that already is part of your list of recent issues.
You should see the toast (was alert before).

Replace default alerts with Toast

---

frontend/src/pages/Report.tsx

The toast appearing after a failing time report attempt was covered by the loading overlay.
The loading overlay is switched off before the warning error is caught
Test a failed report:
* add an invalid combination of issue and activity:
* choose "Design" in the activity dropdown
* type any valid issue number and select the issue
* add it with the plus button
* add a time entry on the newly added row
* press "Save changes"
* you should see the loading overlay for a short while, then it should disappear and a warning toast should be shown
Test a success report: 
* add a time entry to any valid row in your interface
* press "Save changes"
* you should see the same behavior as before: the loading overlay for a short while, then it should disappear and a success toast should be shown

remove loading overlay before warning toast appears

---

frontend/src/components/QuickAdd.tsx
frontend/src/pages/Help.tsx
frontend/src/pages/Report.tsx

This PR closes #461 
- Two new shortcuts were added
- Test the shortcuts when navigating over the spreadsheet

Add shortcuts for save and search focus

---

backend/api/issueSearchHandler.go
frontend/src/components/QuickAdd.tsx

- Use issues redmine api to get issue subjects, since the search api does not return what we want.
- Limit suggestions to 5 hits

Use issues.json to get search issue subjects

---

frontend/src/index.css
frontend/src/pages/Help.tsx

- Use Chrome to test on different mobile screens

Improve mobile UX when using urdr

---

frontend/src/App.tsx
frontend/src/pages/Report.tsx
frontend/src/pages/SpentTime.tsx
frontend/src/utils.tsx

Now we can fetch as many time entries as wanted, without limits.
This PR closes #567
- Navigate to /spent_time

Fetch unlimited time entries

---

frontend/src/components/BarChart.tsx

This PR closes #591
- all activities used in 2021 and 2021 have now a color assigned
- in case an unknown activity is fetched from the database (which shouldn't happen...) there is an escape color
- Absence is excluded from the chart
- go to the report page and look at your bar chart. The biggest categories should have distinct colors, there shouldn't be any two very similar colors next to each other (I really hope that's the case, but it's hard to test as I only see my own reporting. So please let me know if there is anything weird!)

assign colors to activities and remove Absence

---

frontend/src/components/BarChart.tsx
frontend/src/components/Row.tsx
frontend/src/components/Tooltip.tsx
frontend/src/index.css
frontend/src/utils.tsx

This PR closes #592.
- a reusable Tooltip component was created, based on what was already used on the favorite rows
- the tooltip on the favorite rows was replaced by the new component
- the new component was used to show a tooltip on all sections of the bar chart
- the styling of the bar chart had to be slightly adjusted to make the tooltip work (replacing `overflow: hidden` with another border radius)
- go to the report page and hover over the sections of the bar chart. You should see the tooltip appearing above
- also try to hover over the favorite rows. You should see the same tooltip as before

Create reusable tooltip for bar chart

---

frontend/src/index.css

This PR closes #611
- the CSS property `display: block ruby` was removed because it's not supported in Chrome
- instead the `<p>` tags in the label are prevented from line-wrapping
- Check the bar chart in several browsers, especially Chrome

Prevent bar chart from expanding

---

frontend/src/pages/VacationPlanner.tsx

This PR closes #622 
1) Updated visualization to show ranges
2) Added functions to calculate time entry ranges
- Possibly the usual rebuild. It's rebased to current develop

Add time entry range calculations

---

frontend/src/components/BarChart.tsx
frontend/src/pages/Help.tsx

This PR closes #612, closes #619 and closes #620.
- the time span for the bar chart was extended to the full current year
- the heading for the bar chart was changed
- a section for the bar chart on the help page was added
- Go to the report page and log some time during different times. Only time entries between Jan 1st 2022 and Dec 31st 2022 should be represented in the chart.
- Read the help page section and check if it's complete, correct and understandable.

Bar chart fixes and help page

---

docker-compose.yml
node/Dockerfile

This oversight should have been part of #625, related to #624 (now closed).

Use `nginx:1.23.1-alpine` in development too

---

frontend/src/components/QuickAdd.tsx
frontend/src/index.css
frontend/src/pages/Report.tsx

This PR closes #588
- the heading was removed
- instead, the add-button has an explanatory text
- the unsaved changes warning only takes space when it's actually displayed
- the labels are slightly smaller
- the issue label is shortened and combined with a placeholder that provides an example
- some padding was removed
- bootstrap classes were removed and replaced by flexboxes that better fit our needs
- on mobile view / extreme zoom, the elements in the footer wrap below each other 
- try and play with the page:
- in several screen sizes and zoom-levels
- in different browsers
- search for different things in different sizes
- have some unsaved changes and combine with different screen sizes, browsers and search terms

Shrink footer section desktop & mobile

---

frontend/src/index.css
frontend/src/pages/Help.tsx

This PR closes #648
- the height property on the `.quick-add`  class was removed
- the `.footer-container` class was modified to prevent the input elements in the footer from moving when the unsaved changes warning is displayed.
This bug is about the autocomplete box appearing when you search for an issue as well as the unsaved-changes-warning. Play around with these two in mobile and desktop view and see if everything looks good. 
The warning should appear above the save button when you have unsaved changes. The footer should slightly expand for this, but all the elements within the footer should stay in place. 
When you start searching with free text in the issue input field, the box with suggestions should appear below, moving the input elements above it higher up.

fix autocomplete in footer

---

frontend/src/index.css
frontend/src/pages/AbsencePlanner.tsx

This PR closes #599 
We still need the UI component for specifying the new ranges, which could be another issue.
- New function which allows updating existing absence ranges
- Added better error handling
- Test creating, editing and removing
- At the moment, the edit button will update the absence range to be as of the date of the current day

Add function for editing absence ranges

---

frontend/src/pages/Help.tsx

This PR closes #662 
- Added short desc about absence page

Update help page with absence page text

---

backend/api/handlers_test.go
backend/internal/database/userGroups_test.go

This PR closes #607 
* Unit tests were implemented for the database API to ensure that fetching information related to users and groups is working and so that the correct data is returned in the expected manner.
* Simple unit tests were implemented for the endpoint API to ensure that the endpoints reply with OK.
Run the unit tests as usual, from the `backend` subdirectory:
```
go test -v ./...
```

Unit tests for user group code

---

frontend/Dockerfile.update-package-lock

This PR changes the Docker base image in the `frontend` directory so that it is the same as used in the `node` Dockerfile.
This PR closes #692 
Use the image based on Alpine Linux rather than `slim`.  This makes it the same as the image used by the Dockerfile in the `node` subdirectory.

Use the alpine image rather than the slim image

---

.github/dependabot.yml

This PR changes the scheduling for dependabot from "daily" to "weekly".
This change will reduce the number of dependabot PRs we get, allowing us to focus better on other projects. The change is also prompted by the fact that we don't tend to act _immediately_ on seeing these PRs, and that we sometimes even let these PRs time out (get replaced by newer updated PRs).
In the future, when the project is "done", I propose changing the schedule to "monthly".

Change dependabot updates from daily to weekly

---

production/Dockerfile

Fixes a typo that managed to get into the release, breaking the image build.

Continuation line should not have been continuation line

---

production/docker-compose.yml

This tiny PR fixes the production Docker compose file by adding the workaround for the weird Docker network bug that we came across some time ago.  The change makes Urdr use a specific pre-existing Docker network.

Add the workaround for that weird Docker network bug

---

backend/api/api.go
backend/api/getActivitiesHandler.go
backend/api/getPriorityEntriesHandler.go
backend/api/handlers_test.go
backend/api/postTimeEntriesHandler.go
backend/internal/redmine/models.go
frontend/src/components/QuickAdd.tsx
frontend/src/model.tsx
frontend/webpack.config.js

This PR closes #846 
- Frontend changes to use the updated /api/activities endpoint
- Updated /api/activities to use redmine /projects instead of /enumerations
This way we can get the actual activity entries that are allowed by redmine.
- Connect urdr to the production redmine
- Try to report using the Implementation activity to the GDI issue
- Run the unit tests
For more context, read the related issue.

fix: fetch activities from /projects

---

production/docker-compose.yml

This corresponds to the live changes made on the 31st of October when a Docker-related networking issue forced us to move the service into an LXC container.  The use of an external Docker network was a hack to cope with an earlier Docker network issue.  That issue was resolved when setting up the service in LXC.

Remove use of external Docker network

---

backend/api/postTimeEntriesHandler.go

This PR closes #955 
When detecting that a time entry should be _deleted_, the request body is deleted.  This avoids a complaint from any intermediate network proxy from complaining about the request.
To test the change, you will have to reproduce the error.  You can do that by setting up a local HAProxy instance between your Urdr instance and Redmine, like this:
0. Possibly, create a temporary empty directory and change into it.
1. Create a HAProxy configuration file, `haproxy.cfg`, containing the following:
```
listen redmine
bind :80
mode http
server localhost 192.168.1.20:3000
```
Change `192.168.1.20:3000` to the Redmine instance that you want to connect to.
2. Start the `haproxy` Docker container running in the background:
```
docker run -d --rm -p 3333:80 --name haproxy -v …
```

Delete the request body when changing the method to "DELETE"

---

backend/Dockerfile
docker-compose.yml
node/Dockerfile
production/Dockerfile
production/docker-compose.yml

This PR relates to #977.
This PR should fix the automatic Docker image builds that are done by Github actions when we push to the `develop` branch. The issue was that the `production` Dockerfile tried to install a too-old version of the `gcc` compiler. This has been resolved, and the `backend` Dockerfile has been amended to use the same `golang` base image.
As suggested by other dependabot PRs, also bump the Go version to 1.23 while we're here.
Ensure that `docker compose build` succeeds in both the `production` subdirectory (where it fails without this PR), and in the main directory.

Bump gcc version and use Alpine 3.20 base image

---

backend/api/getPriorityEntriesHandler.go

The `issues.json` Redmine endpoint does not, by default, return data for closed issues.  This means that when a user has starred a Redmine issue that later is _closed_, Urdr can't find any information about it and panics.  The panic is due to accessing the first element from an empty array, which is empty because there was no information from Redmine about the issue, because it was closed.
This PR closes #1002.
This PR allows us to find the project ID for closed Redmine issues that a user has starred in Urdr.  This is done by adding `status_id=*` as a query parameter to the relevant REST API call.
To test: Star a closed issue (for example 7398) and reload.  You will have problem seeing your favourites.
With the PR, this should work.

Fix Urdr panic when user has starred a closed issue

---

frontend/src/pages/Report.tsx

This PR closes https://github.com/NBISweden/urdr/issues/906 
- Used the already existing `isLoading` state to trigger the loading spinner when the data is still fetched. 
- Added a check in the `getRowData`-function so that it wouldn't be called twice, first when `recentIssues` is empty and then again when `recentIssues` is populated. 
- Added `await` in front of `getAllEntries` to ensure that the function completes its asynchronous operations before proceeding.
1. Check out this branch and get both urdr and redmine up an running. Urdr-repo: https://github.com/NBISweden/urdr  Redmine-repo:https://github.com/NBISweden/ops-redmine
2. Log in if needed
3. Refresh the page and watch the spinner appear and then disappear when the data is loaded.
4. Go to a new week and see the spinner appear …

Feat: display loading spinner until data is loaded

---

frontend/src/components/Row.tsx
frontend/src/pages/Report.tsx

This PR closes #1037.
* Updated the display logic for total hours cells to remain empty until all time entries are loaded, instead of displaying potentially misleading zero values.
- Navigate to the report page and verify that the total hours cells (to the right and at the bottom) are empty while the time entries are being loaded. Once the loading is complete, confirm that the cells display the correct sum of hours for each row and column.
- Switch to another week and verify that the behavior is consistent.

fix: show empty total hours cells during data load

---

frontend/src/App.tsx

This PR closes #1031
- use `getISOWeekYear` instead of `getFullYear` to avoid mismatch between week and year during the last or first week of a year. 
- Read more about the function in the  [date library's documentation](https://date-fns.org/v4.1.0/docs/getISOWeekYear)
I really don't know how to test this because it only happens on certain dates. 
I suppose you could fiddle with your computer's date settings but I didn't do that. So I actually didn't test this and trust the date library's documentation. At least it doesn't break functionality during the rest of the year, as far as I can see.

use getISOWeekYear to determine current year

---

frontend/src/pages/Report.tsx

This PR closes #1036 
- time entries for one week are now fetched in one call to the Redmine API instead of row by row
On the develop branch: 
- open your local urdr in the browser
- switch between weeks and look at the network tab in the dev tools: you will see one API call per row. In my setup, each one took between 100 and 200ms.
On this PR's git branch:
- do the same as above: you will see only one API call for the time entries of the current week. In my setup it took between 200 and 400ms --> much less than the sum of all displayed rows.
The page load is still somewhat slow due to a slow fetch of `priority_entries`. That fetch is not connected to Redmine but to our own API and database and should be optimized there. There is a [follow-up …

Optimize fetching of time entries

---

frontend/webpack.config.prod.js

Hotfix: Apply the development changes to the production webpack config. Causes JS errors relating to `process` otherwise.
Once this is merged, I'll make a new release.
The `webpack.config.prod.js` lacked the setting of the `gitHash` and `gitBranch` variables from the environment.
Testing:
```
$ git pull
$ git checkout release/20250319
$ git pull
$ cd production
$ cat undr.env    # to see that it exists and that it looks valid
$ docker compose build
$ docker up
```
Check browser.

fix: Apply the development changes to the production webpack config

---

.github/dependabot.yml

According to a team discussion to merge dependabot PR:s into a larger branch there is a new functionality in dependabot where you can automatically group dependabot PR:s. 
[Github documentation](https://docs.github.com/en/code-security/dependabot/working-with-dependabot/dependabot-options-reference#groups) about dependabot
Check [this article](https://slar.se/dependabots-dependency-grouping.html) which I followed to make the suggested changes
Under each package ecosystem I added the groups attribute, a name and a wildcard pattern. The name will be used in the PR and the pattern takes everything under the specific folder
I don't know how to test this in advance than see what the next dependabot will do
This is experimental so let me know your thoughts

feat: grouping dependabot PRs automatically

---

frontend/src/pages/Report.tsx

This PR closes #1084.
- The total hours are now displayed when time entries are being added to a new, unsaved week
- Add time to a new, unsaved week and verify that the total hours are shown before (and after...) saving.

fix: show sums when editing new week

---

.github/workflows/create_packages.yml

This PR closes #1093 
The `create_packages.yml` GitHub workflow will no longer trigger for merges to the `develop` branch.

fix: Don't build containers or bump version on "develop" branch

---

.github/dependabot.yml

This PR tweaks the dependabot grouping of Docker-related dependencies by adding them to the same "dependency group" regardless of which project directory the corresponding files are in.
This makes it easier to ensure that Docker dependencies are in sync across the project.

fix: Collect all Docker dependency updates in the same "dependency group"

---

.github/dependabot.yml

Another go at getting the Docker dependency updates grouped.

fix: Collect all Docker dependency updates in a single group

---

frontend/src/pages/AbsencePlanner.tsx

This PR closes issue #1068 .
In the absence planner view
- only absence periods with 8 hours logged per day are shown 
- only absence periods that end today or later are shown
- To make sure that you can see the changes of this PR you will need to log some absence periods, manually or using the absence planner tool:
1. a full-time absence starting and ending in the past
2. a full-time absence starting in the past and ending today
3. a full-time absence starting in the past and ending in the future
4. a full-time absence starting and ending in the future
5. a part-time absence starting and ending in the future
- look at the absence planner page. You should only see periods 2, 3 and 4.
Apart from the above mentioned changes this PR also extends the period that is searched for absences to …

Show only full-time absence in the past

---

frontend/src/components/VacationOverview/GroupSelect.tsx

This PR relates to #1094 . 
A change from group. name to group.id caused the dropdown to stop working.
- Changing the arguments from string -> number

fix: fixing the groupSelect to take number as a parameter

---

frontend/src/components/VacationOverview/VacationOverview.tsx
frontend/src/components/VacationOverview/utils.ts
frontend/src/model.tsx

This PR closes #1095.
This PR adds the functionality to save the selected group in the group selector so that the user does not have to select the group every time he/she navigates to the Absence page.
More details about the endpoint `api/setting` can be found in [this PR](https://github.com/NBISweden/urdr/pull/1104).
- Added a new function, `getGroupSetting`, which, given that the user has a saved group, will return the group id. If `getGroupSetting` returns a group id, that group will be used as the default group in the group selector. If not, the default group will be NBIS staff.
- Added a new function, `saveSettings`. This function is called when the user selects another group (than the one currently saved) in the group selector.
- Refactored the `VacationOverview` component and moved …

feat: save settings for vacation overview groups

---

frontend/src/components/VacationOverview/GroupSelect.tsx
frontend/src/components/VacationOverview/VacationTable.tsx
frontend/src/index.css
frontend/src/pages/VacationOverview.tsx

This PR closes #1136.
- A loading spinner is shown while `vacationData` is being loaded.
- Added a label to the `GroupSelect` component.
- Navigate to http://localhost:4567/vacation, select a group and view the spinner in action.

feat: add loading spinner to vacation overview page

---

frontend/src/components/VacationOverview/utils.ts
frontend/src/pages/VacationOverview.tsx

This PR closes #1146.
- Full-time Parental Leave Indication: If a user has reported full-time (8 hours) parental leave for at least one day in a week, that week will now be marked in the same way as vacation in the vacation overview table.
- Non-Full-Time Parental Leave: If a user has reported less than a full day (i.e., less than 8 hours) or more than a standard full day (i.e., more than 8 hours) of parental leave in a week, and there are no other vacation or full-time parental leave entries for that week, the week will not be marked in the vacation overview table.
1. Navigate to `localhost:4567/report`.
2. Add 8 hours of parental leave on a day in a week with no other vacation or parental leave entries. Navigate to `localhost:4567/vacation` and verify that the week is marked in the …

feat: show full-time parental leave in vacation overview

---

frontend/src/components/QuickAdd.tsx
frontend/src/model.tsx

This PR closes #944.
The users want to search for the WABI id custom field as well to find the issue to report time.
- In quick add component I extended the search to search for the WABI ID in the issues custom fields
- I extended the Issue model to contain a custom fields variable and created a CustomField model. 
- As an administrator check the "use as filter" checkbox in the custom field for WABI ID, found if you go to administration > custom fields and then choose WABI ID custom field
- To find projects with WABI ID to test in the search, go to long term support projects in the local Redmine using the GUI:
- Choose one of the rounds and then look for issues that are in progress so that they have been assigned the WABI ID number.
- For this to work in production a Redmine admin has to …

feat: extended search function to search for WABI ID as well

---

frontend/src/components/VacationOverview/VacationTable.tsx

This PR closes issue #1181 
The legend color is now displayed in front of the legend label for "Vacation" and "Parental leave" on the vacation overview page.
Make sure it looks as described in the issue.

show legend color in front of legend label

---

frontend/src/components/TimeTravel.tsx

This PR closes #1180 
The locale in the date picker on the report page has been changed from "sv" to "enGB"
Make sure that weekdays and the "today" button are displayed in English.

Use english in report date picker

---

frontend/src/components/WeekPicker.tsx

This PR closes #1179  and relates to#1179.
Make week picker start on Monday.
- added locale

Make week picker start with Monday
